### ISSUE TITLE
Alias for python manage.py

### ISSUE THREAD

**Issue by marcosranes** [PortalNetZone/django-app#23]
#### How it works:
1. Once you need to navigate through several levels with cd commands, there will be a given moment that you'll need back or forward to the goal path in order to run the script successfully.
2. So, we're about going to edit our `.bashrc` file to add an environment variable by creating an alias to `python manage.py` command.
3. Also add to it the virtual env default path located into another environment variable, just command `echo $VIRTUAL-ENV` to show its path.
It won't generate a pull request, once the files of the project weren't modified.

You can make it this way...
```
(django-app) marcosranes@ubuntu21-vbox:~$ echo "
> #Defining an alias to manage.py file for reaching different scopes
> alias mng='python $VIRTUAL_ENV/../manage.py'" >> .bashrc

(django-app) marcosranes@ubuntu21-vbox:~$ source .bashrc

marcosranes@ubuntu21-vbox:~$ exit
exit

marcosranes@ubuntu21-vbox:~/Desktop/django-app$ pipenv shell
Launching subshell in virtual environment...
marcosranes@ubuntu21-vbox:~/Desktop/django-app$  . /home/marcosranes/Desktop/django-app/.venv/bin/activate

(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ mng --version
3.2.8
```
Or directly editing the `.bashrc` file. located at your home `~/.bashrc`

**Comment by marcosranes** [comment]
```
marcosranes@ubuntu21-vbox:~/Desktop/django-app$ echo $VIRTUAL_ENV

marcosranes@ubuntu21-vbox:~/Desktop/django-app$ pipenv shell
Launching subshell in virtual environment...
marcosranes@ubuntu21-vbox:~/Desktop/django-app$  . /home/marcosranes/Desktop/django-app/.venv/bin/activate
(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ echo $VIRTUAL_ENV
/home/marcosranes/Desktop/django-app/.venv
(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ ls -a
.          coverage.xml  .flake8     .idea      Pipfile       .pytest_cache  .travis.yml
..         db.sqlite3    .git        LICENSE    Pipfile.lock  .pyup.yml      .venv
.coverage  django-app    .gitignore  manage.py  pypro         README.md
(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ python manage.py --version
3.2.8
(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ cd ..
(django-app) marcosranes@ubuntu21-vbox:~/Desktop$ python manage.py --version
python: can't open file '/home/marcosranes/Desktop/manage.py': [Errno 2] No such file or directory
(django-app) marcosranes@ubuntu21-vbox:~/Desktop$ cd django-app/
(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ python manage.py --version
3.2.8
(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ python $VIRTUAL_ENV/../manage.py --version
3.2.8
(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ cd ..
(django-app) marcosranes@ubuntu21-vbox:~/Desktop$ python $VIRTUAL_ENV/../manage.py --version
3.2.8
(django-app) marcosranes@ubuntu21-vbox:~/Desktop$ cd ..
(django-app) marcosranes@ubuntu21-vbox:~$ python $VIRTUAL_ENV/../manage.py --version
3.2.8
(django-app) marcosranes@ubuntu21-vbox:~$ ls -a
.              .dbus        .java     .pyenv                            .vboxclient-draganddrop.pid
..             Desktop      .local    snap                              .vboxclient-seamless.pid
.bash_history  Documents    .mozilla  .ssh                              Videos
.bash_logout   Downloads    Music     .sudo_as_admin_successful         .zcompdump
.bashrc        .fontconfig  Pictures  Templates
.cache         .gitconfig   .pki      .thunderbird
.config        .gnupg       .profile  .vboxclient-clipboard.pid
.cups          .hardinfo    Public    .vboxclient-display-svga-x11.pid

(django-app) marcosranes@ubuntu21-vbox:~$ echo "
> #Defining an alias to manage.py file for reaching different scopes
> alias mng='python $VIRTUAL_ENV/../manage.py'" >> .bashrc
(django-app) marcosranes@ubuntu21-vbox:~$ cat .bashrc 
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
# eval "$(pyenv virtualenv-init -)"

#Allows Pipenv to create the virtual environment folder within the project
#directory instead of the standard path that it sugests by default.
export PIPENV_VENV_IN_PROJECT=1

#Pycharm launcher script
#alias charm="/usr/local/bin/charm"
alias charm="/snap/pycharm-community/252/bin/pycharm.sh"

#bind for activating the sharing to WinShare folder
alias share="sudo mount -t vboxsf WinShare ~/Desktop/WinShare/"

#Defining an alias to manage.py file for reaching different scopes
alias mng='python /home/marcosranes/Desktop/django-app/.venv/../manage.py'

(django-app) marcosranes@ubuntu21-vbox:~$ source .bashrc 
marcosranes@ubuntu21-vbox:~$ pipenv shell
Shell for /home/marcosranes/Desktop/django-app/.venv already activated.
No action taken to avoid nested environments.
marcosranes@ubuntu21-vbox:~$ mng --version
Traceback (most recent call last):
  File "/home/marcosranes/Desktop/django-app/.venv/../manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marcosranes/Desktop/django-app/.venv/../manage.py", line 22, in <module>
    main()
  File "/home/marcosranes/Desktop/django-app/.venv/../manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
marcosranes@ubuntu21-vbox:~$ exit
exit
marcosranes@ubuntu21-vbox:~/Desktop/django-app$ pipenv shell
Launching subshell in virtual environment...
marcosranes@ubuntu21-vbox:~/Desktop/django-app$  . /home/marcosranes/Desktop/django-app/.venv/bin/activate
(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ mng --version
3.2.8
(django-app) marcosranes@ubuntu21-vbox:~/Desktop/django-app$ cd /
(django-app) marcosranes@ubuntu21-vbox:/$ mng --version
3.2.8
(django-app) marcosranes@ubuntu21-vbox:/$ cd ~
(django-app) marcosranes@ubuntu21-vbox:~$ mng --version
3.2.8
(django-app) marcosranes@ubuntu21-vbox:~$ AS YOU CAN SEE, MNG ALIAS CAN BE REACHED FOR ALL SCOPES NOW
```
